# Change these first
owner: klentelevisit # Your GitHub organization or username, where this repository lives
repo: siteUptime # The name of this repository

sites:
  - name: TelevisitMD
    url: http://televisitmd.com/
  - name: LT
    url: https://tvmdlt.com/
  - name: MD-Do
    url: http://md-do.doctor/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /siteUptime
  logoUrl: https://www.televisitmd.com/wellness/wp-content/uploads/2022/09/Televisit-Logo.png
  name: Upptime
  introTitle: "**TelevisitMD ** Uptime Checker"
  introMessage: This status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
